---
profile_homebrew_taps: []

profile_homebrew_packages:
  - docker
  - docker-compose
  - node
  - maven
  - jenv
  - pyenv

profile_homebrew_cask_apps:
  - slack
  - zoom
  - visual-studio-code
  - docker
  - sourcetree
  - android-studio
  - iterm2

profile_mas_apps: []